services:
  clickupbot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "0.0.0.0:32361:3000"
    restart: always
    volumes:
      - ./userData.json:/app/userData.json
